var cards = [
{
  cardId: 8,
  cardImage: "img/cards/venture.png",
  name: "Venture",
  issuer: "CapitalOne",
  credit: "Excellent",
  APR: "13.90% - 20.90%",
  transferAPR: "13.90%",
  transferFee: "$0",
  annualFeeFirst: "$0",
  annualFeeSub: "$59",
  cashReward: "null",
  milesRewards: "2x miles for everything",
  introCashBack: "null",
  miles: "40,000 bonus miles when you spend $3,000 in the first 3 months",
  third: "40,000 bonus miles when you spend $3,000 in the first 3 months.", // in the first 3 months",
  cashadvance: "24.9%",
  customDesign: "1",
  link: "http://www.capitalone.com/credit-cards/venture",
  misc: "Capital One Credit Tracker"
},
{
  cardId: 2,
  cardImage: "img/cards/british.png",
  name: "British Airways",
  issuer: "Chase",
  credit: "Excellent",
  APR: "15.99%",
  transferAPR: "null",
  transferFee: "null",
  annualFeeFirst: "$0",
  annualFeeSub: "$95",
  cashReward: "null",
  milesRewards: "2.5 Avios for every $1 spent on British Airways and 1.25 per $1 on other purchases.*", // purchases and 1.25 Avios for every $1 spent on all other purchases; No foreign transaction fees",
  third: "2.5 Avios for every $1 spent on British Airways and 1.25 per $1 on other purchases.*", // purchases and 1.25 Avios for every $1 spent on all other purchases; No foreign transaction fees",
  introCashBack: "null",
  miles: "50,000 bonus Avios after you make $2,000 in purchases within the first 3 months of account opening",
  cashAdvance: "19.24%",
  customDesign: "1",
  link: "https://creditcards.chase.com/a1/ba/affiliates?AFFID=SWlnSnn6x54-wzzlsWZ8A0L_IYJ_HypJ7Q&pvid=4d7b6becbb492b3b&jp_cmp=cc/355863/aff/2-31327/na",
  misc: "Every calendar year you make $30,000 in purchases on your British Airways Visa Card, you'll earn a Travel Together Ticket good for two years."
},

{
  cardId: 10,
  cardImage: "img/cards/wf.png",
  name: "Wells Fargo Rewards",
  issuer: "Wells Fargo",
  credit: "Good",
  APR: "12.15% - 25.99%",
  transferAPR: "12.15%",
  transferFee: "Introductory fee of either $5 or 3% of the amount of each balance transfer, whichever is greater, for 15 months",
  annualFeeFirst: "$0",
  annualFeeSub: "$0",
  cashReward: "null",
  milesRewards: "Earn 1 rewards point for every $1 spent on virtually all net purchases.*",
  third: "Earn 1 rewards point for every $1 spent on virtually all net purchases.*", // on virtually all other net purchases everyday.",
  introCashBack: "null",
  miles: "Earn 5 X rewards points for every $1 spent on gas, grocery, and drugstore net purchases for the first 6 months",
  fee: "Either $10 or 5% of the amount of each advance, whichever is greater",
  cashAdvance: "23.99% - 25.99%",
  customDesign: "2",
  link: "https://www.wellsfargo.com/credit-cards/rewards/",
  misc: "Wells Fargo Credit Defense Platinum service"
},
{
  cardId: 4,
  cardImage: "img/cards/journey.png",
  name: "Journey Student",
  issuer: "CapitalOne",
  credit: "Good",
  APR: "19.8%",
  transferAPR: "19.8%",
  transferFee: "null",
  annualFeeFirst: "$0",
  annualFeeSub: "$0",
  cashRewards: "1% cash back on all purchases",
  third: "1% cash back on all purchases", //, plus a 25% bonus on the cash back you earn each month you pay on time",
  milesRewards: "null",
  introCashBack: "null",
  miles: "null",
  fee: "Either $10 or 3% of the amount of each cash advance, whichever is greater",
  cashAdvance: "19.8%",
  customDesign: "1",
  link: "https://www.capitalone.com/credit-cards/journey-student",
  misc: "No foreign transaction fee on purchases"

},
{
  cardId: 0,
  cardImage: "img/cards/accountnow.png",
  name: "AccountNow Gold Visa Prepaid Card",
  issuer: "AccountNow",
  credit: "Poor",
  APR: "0%",
  transferAPR: "null",
  annualFeeFirst: "$0",
  annualFeeSub: "$9.95/mo",
  cashRewards: "$15 bonus with direct deposit of at least $500/mo within 6 mo.",
  third: "$15 bonus with direct deposit of at least $500/mo within 6 mo.", // of opening account.",
  milesRewards: "null",
  introCashBack: "null",
  miles: "null",
  fee: "2.5 atm withdrawl; $0 if cash back from cashier",
  cashAdvance: "null",
  customDesign: "1",
  link: "https://www.accountnow.com/secure/signup2.aspx",
  misc: "No foreign transaction fee on purchases"

},
{
  cardId: 1,
  cardImage: "img/cards/bofa.png",
  name: "BankAmericard Cash Rewards Card",
  issuer: "Bank of America",
  credit: "Good",
  APR: "12.99% - 22.99%",
  transferAPR: "12.99%",
  transferFee: "3% of each transaction (minimum of $10)",
  annualFeeFirst: "$0",
  annualFeeSub: "$0",
  cashRewards: "1% on all purchases; 2% at grocery stores; 3% on gas",
  milesRewards: "null",
  introCashBack: "Online-exclusive $100 cash rewards bonus after at least $500 in purchases.*",
  third: "Online-exclusive $100 cash rewards bonus after at least $500 in purchases.*", // after making at least $500 in purchases in the first 90 days of your account opening",
  miles: "null",
  fee: "Either $10 or 3% of the amount of each transaction, whichever is greater",
  cashAdvance: "15.99% - 24.99%",
  customDesign: "2",
  link: "https://www.bankofamerica.com/credit-cards/products/cash-back-credit-card.go",
  misc: "Auto rental collision damage waiver"

},
{
  cardId: 5,
  cardImage: "img/cards/nfl.png",
  name: "NFL Extra Points Credit Card",
  issuer: "Barclays",
  credit: "Excellent",
  APR: "14.99% - 24.99%",
  transferAPR: "0% Intro APR for 15 months on balance transfers made within 45 days of account opening; 14.99%,19.99% or ",
  annualFeeFirst: "$0",
  annualFeeSub: "$0",
  cashRewards: "2 points per $1 on game tickets",
  milesRewards: "null",
  introCashBack: "$100 cash back credit after $500 in purchases within the first 90 days.*",
  third: "$100 cash back credit after $500 in purchases within the first 90 days.*", // of account opening – enough to redeem for a $100 cash back statement credit",
  miles: "null",
  fee: "null",
  cashAdvance: "null",
  customDesign: "2",
  link: "http://www.nflextrapoints.com/nfl-extra-points-credit-card/?campaignId=203",
  misc: "20% off at nflshop.com"

},
{
  cardId: 3,
  cardImage: "img/cards/slate.png",
  name: "Chase Slate",
  issuer: "Chase",
  credit: "Good",
  APR: "12.99% - 22.99%",
  transferAPR: "12.99% to 22.99%",
  transferFee: "3% of the amount transferred, with a minimum of $5",
  third: "3% of the amount transferred, with a minimum of $5",
  annualFeeFirst: "$0",
  annualFeeSub: "$0",
  cashRewards: "null",
  milesRewards: "null",
  introCashBack: "null",
  miles: "null",
  fee: "Either $10 or 3% of the amount of each transaction, whichever is greater",
  cashAdvance: "23.99%",
  customDesign: "1",
  link: "https://creditcards.chase.com/credit-cards/slate.aspx",
  misc: "Purchase protection"

},
{
  cardId: 7,
  cardImage: "img/cards/sw.png",
  name: "Southwest Airlines Rapid Rewards Premier Card",
  issuer: "Chase",
  credit: "Good",
  APR: "15.99%",
  transferAPR: "15.99%",
  transferFee: "Either $5 or 3% of the amount of each transfer, whichever is greater",
  annualFeeFirst: "$99",
  annualFeeSub: "$99",
  cashRewards: "null",
  milesRewards: "Earn 2 points for every $1 you spend on Southwest Airlines purchases made directly with the airlines. Also, 2 points per $1 you spend on Southwest Rapid Rewards Hotel and Car Rental Partner purchases.",
  introCashBack: "null",
  miles: "50,000 points after you spend $2,000*",
  third: "50,000 points after you spend $2,000*", // on purchases in the first 3 months of opening your account.",
  fee: "Either $10 or 5% of the amount of each transaction, whichever is greater",
  cashAdvance: "19.24%",
  customDesign: "1",
  link: "https://creditcards.chase.com/credit-cards/southwest-credit-card.aspx",
  misc: "Your bags fly free"

},
{
  cardId: 6,
  cardImage: "img/cards/qw.png",
  name: "Quicksilver",
  issuer: "CapitalOne",
  credit: "Excellent",
  APR: "12.90% - 22.90%",
  transferAPR: "15.99%",
  transferFee: "3% of the amount transferred until November 2015",
  annualFeeFirst: "$0",
  annualFeeSub: "$0",
  cashRewards: "Unlimited 1.5% cash back on every purchase",
  milesRewards: "null",
  introCashBack: "$100 Cash Bonus.*",
  third: "$100 Cash Bonus.*", //Earn a one-time bonus by spending $500 on purchases within the first 3 months.",
  miles: "null",
  fee: "null",
  cashAdvance: "24.90%",
  customDesign: "1",
  link: "http://www.capitalone.com/credit-cards/quicksilver/",
  misc: "Capital One Credit Tracker"

},
{
  cardId: 9,
  cardImage: "img/cards/advantageOne.png",
  name: "Visa Platinum",
  issuer: "Advantage One",
  credit: "Good",
  APR: "9.99% - 17.99%",
  transferAPR: "9.99% - 17.99%",
  transferFee: "$0",
  third: "$0 Transfer Fee",
  annualFeeFirst: "$0",
  annualFeeSub: "$0",
  cashRewards: "null",
  milesRewards: "null",
  introCashBack: "null",
  miles: "null",
  fee: "null",
  cashAdvance: "null",
  customDesign: "2",
  link: 'http://www.advantageonefcu.com/VisaPlatinum',
  misc: "Lost or Stolen Card Reporting"

}
]